[package]
name = "kern"
version = "0.1.0"
edition = "2024"

[lib]
name = "partial_kernel_rs"
path = "./kernel.rs"
test = false
bench = false
crate-type = [ "staticlib" ]


[dependencies]
_410kern = { path = "../410kern" }
num-traits = { version = "*", default-features = false }
elain = "*"
paste = "1.0"

[profile.dev]
panic = "abort"
lto = "thin"

[profile.release]
panic = "abort"
lto = "thin"
